### ISSUE TITLE
arnoudb.WRI\input.txt data missed

### ISSUE THREAD

**Issue by j0k** [arnoudbuzing/neural-network-experiments#2]
It will be useful to put file into repo to get lucky with
`"data = Import["c:\\Users\\arnoudb.WRI\\input.txt", "Text"];"`

**Comment by arnoudbuzing** [comment]
Done. I think with more recent versions of the Wolfram Language you can implement this sort of thing more directly with high level documented functions. I haven't looked into this closely yet, though.
